#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/.local/share/go
export JAVA_HOME="$(find /usr/lib/jvm -maxdepth 1 | grep openjdk | awk -F '-' '$2>count {count=$2; java_home=$0} END {print java_home}')"
export PATH="$JAVA_HOME/bin:$PATH"
export LS_COLORS="$($HOME/.config/scripts/dir2ls_colors $HOME/.config/ls_colors/dircolor)"